name: FAIR Data Pipeline Action
author: Scottish COVID Response Consortium
description: Adds full install of the FAIR Data Pipeline registry and Command Line Interface
inputs:
  registry_tag:
    description: Use a tagged release of the FAIR registry
    required: false
    default: ''
  cmd:
    description: Command to run
    required: false
    default: ''
  project_directory:
    description: Location for initialisation
    required: false
    default: ''
  registry_directory:
    description: Directory for registry installation
    required: false
    default: /home/fairci
  cli_branch:
    description: Git branch for CLI
    required: false
    default: dev
runs:
  using: docker
  image: Dockerfile
branding:
  icon: database
  color: gray-dark