name: FAIR Data Pipeline Action
author: Scottish COVID Response Consortium
description: Adds full install of the FAIR Data Pipeline registry and Command Line Interface
inputs:
  local_registry:
    description: Location in which to install local registry
    required: false
    default: ''
  remote_registry:
    description: Location in which to install remote registry
    required: false
    default: ''
  directory:
    description: Location of FAIR project for initialisation relative to runner directory
    required: false
    default: ''
  ref:
    description: Reference to use for FAIR-CLI
    required: false
    default: latest
runs:
  using: docker
  image: Dockerfile
branding:
  icon: terminal
  color: gray-dark