name: FAIR Data Pipeline Action Check
on: [push]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Create pretend project
          run: mkdir my_project
        - uses: FAIRDataPipeline/fair-setup-action@testing
          with:
            directory: my_project
            local_registry: local_registry
            remote_registry: remote_registry
            ref: develop
        - name: Run Hello World!
          run: |
            git remote add origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git || true
            git fetch --all
            fair create --debug
            fair run --script 'echo "Hello World!"' --dirty
            fair log
          working-directory: my_project