name: FAIR Data Pipeline Action Check
on: [push]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Create pretend project
          run: mkdir my_project
        - uses: FAIRDataPipeline/fair-setup-action@testing
          with:
            cmd: run
            directory: my_project