name: FAIR Data Pipeline Action Check
on: [push]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: FAIRDataPipeline/fair-setup-action@testing
        - run: fair init --ci
        - run: fair run --ci